// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetingService.proto

package com.jbksoft.protobufferrpc.protobufferrpcData;

public final class MyGreetingService {
  private MyGreetingService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf service {@code protobufDemo.Greeting}
   */
  public static abstract class Greeting
      implements com.google.protobuf.Service {
    protected Greeting() {}

    public interface Interface {
      /**
       * <code>rpc sayHello(.protobufDemo.HelloRequest) returns (.protobufDemo.HelloReply);</code>
       */
      public abstract void sayHello(
          com.google.protobuf.RpcController controller,
          com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest request,
          com.google.protobuf.RpcCallback<com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new Greeting() {
        @java.lang.Override
        public  void sayHello(
            com.google.protobuf.RpcController controller,
            com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest request,
            com.google.protobuf.RpcCallback<com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply> done) {
          impl.sayHello(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.sayHello(controller, (com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc sayHello(.protobufDemo.HelloRequest) returns (.protobufDemo.HelloReply);</code>
     */
    public abstract void sayHello(
        com.google.protobuf.RpcController controller,
        com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest request,
        com.google.protobuf.RpcCallback<com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.jbksoft.protobufferrpc.protobufferrpcData.MyGreetingService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.sayHello(controller, (com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest)request,
            com.google.protobuf.RpcUtil.<com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.jbksoft.protobufferrpc.protobufferrpcData.MyGreetingService.Greeting implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void sayHello(
          com.google.protobuf.RpcController controller,
          com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest request,
          com.google.protobuf.RpcCallback<com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply.class,
            com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply sayHello(
          com.google.protobuf.RpcController controller,
          com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply sayHello(
          com.google.protobuf.RpcController controller,
          com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.HelloReply.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:protobufDemo.Greeting)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GreetingService.proto\022\014protobufDemo\032\016t" +
      "estData.proto2L\n\010Greeting\022@\n\010sayHello\022\032." +
      "protobufDemo.HelloRequest\032\030.protobufDemo" +
      ".HelloReplyBE\n-com.jbksoft.protobufferrp" +
      "c.protobufferrpcDataB\021MyGreetingService\210" +
      "\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jbksoft.protobufferrpc.protobufferrpcData.GreetingProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
