// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonAccount.proto

package com.jbksoft.protobuf.protobufferData;

public final class PersonAccountsBookProtos {
  private PersonAccountsBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
     *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
     *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
     * </pre>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
     *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
     *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
     *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
     *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 id = 2;
    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated .protobufDemo.Person.AccountNumber accounts = 4;
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber> 
        getAccountsList();
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber getAccounts(int index);
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    int getAccountsCount();
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    java.util.List<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder> 
        getAccountsOrBuilderList();
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder getAccountsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobufDemo.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                accounts_ = new java.util.ArrayList<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber>();
                mutable_bitField0_ |= 0x00000008;
              }
              accounts_.add(input.readMessage(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          accounts_ = java.util.Collections.unmodifiableList(accounts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.class, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobufDemo.Person.AccountType}
     */
    public enum AccountType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHECKING = 0;</code>
       */
      CHECKING(0, 0),
      /**
       * <code>SAVING = 1;</code>
       */
      SAVING(1, 1),
      /**
       * <code>VISA = 2;</code>
       */
      VISA(2, 2),
      ;

      /**
       * <code>CHECKING = 0;</code>
       */
      public static final int CHECKING_VALUE = 0;
      /**
       * <code>SAVING = 1;</code>
       */
      public static final int SAVING_VALUE = 1;
      /**
       * <code>VISA = 2;</code>
       */
      public static final int VISA_VALUE = 2;


      public final int getNumber() { return value; }

      public static AccountType valueOf(int value) {
        switch (value) {
          case 0: return CHECKING;
          case 1: return SAVING;
          case 2: return VISA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AccountType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<AccountType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AccountType>() {
              public AccountType findValueByNumber(int number) {
                return AccountType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final AccountType[] VALUES = values();

      public static AccountType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private AccountType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobufDemo.Person.AccountType)
    }

    public interface AccountNumberOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string number = 1;
      /**
       * <code>required string number = 1;</code>
       */
      boolean hasNumber();
      /**
       * <code>required string number = 1;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>required string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      // optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];
      /**
       * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
       */
      boolean hasType();
      /**
       * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
       */
      com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType getType();
    }
    /**
     * Protobuf type {@code protobufDemo.Person.AccountNumber}
     */
    public static final class AccountNumber extends
        com.google.protobuf.GeneratedMessage
        implements AccountNumberOrBuilder {
      // Use AccountNumber.newBuilder() to construct.
      private AccountNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private AccountNumber(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final AccountNumber defaultInstance;
      public static AccountNumber getDefaultInstance() {
        return defaultInstance;
      }

      public AccountNumber getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private AccountNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                number_ = input.readBytes();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType value = com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_AccountNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_AccountNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.class, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder.class);
      }

      public static com.google.protobuf.Parser<AccountNumber> PARSER =
          new com.google.protobuf.AbstractParser<AccountNumber>() {
        public AccountNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new AccountNumber(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<AccountNumber> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string number = 1;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private java.lang.Object number_;
      /**
       * <code>required string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];
      public static final int TYPE_FIELD_NUMBER = 2;
      private com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType type_;
      /**
       * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType getType() {
        return type_;
      }

      private void initFields() {
        number_ = "";
        type_ = com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType.SAVING;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobufDemo.Person.AccountNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_AccountNumber_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_AccountNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.class, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder.class);
        }

        // Construct using com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType.SAVING;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_AccountNumber_descriptor;
        }

        public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber getDefaultInstanceForType() {
          return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.getDefaultInstance();
        }

        public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber build() {
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber buildPartial() {
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber result = new com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.number_ = number_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber) {
            return mergeFrom((com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber other) {
          if (other == com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.getDefaultInstance()) return this;
          if (other.hasNumber()) {
            bitField0_ |= 0x00000001;
            number_ = other.number_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasNumber()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string number = 1;
        private java.lang.Object number_ = "";
        /**
         * <code>required string number = 1;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string number = 1;</code>
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }

        // optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];
        private com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType type_ = com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType.SAVING;
        /**
         * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
         */
        public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType getType() {
          return type_;
        }
        /**
         * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
         */
        public Builder setType(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .protobufDemo.Person.AccountType type = 2 [default = SAVING];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountType.SAVING;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobufDemo.Person.AccountNumber)
      }

      static {
        defaultInstance = new AccountNumber(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protobufDemo.Person.AccountNumber)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
     *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
     *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
     *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
     *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
     *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
     *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .protobufDemo.Person.AccountNumber accounts = 4;
    public static final int ACCOUNTS_FIELD_NUMBER = 4;
    private java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber> accounts_;
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    public java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber> getAccountsList() {
      return accounts_;
    }
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    public java.util.List<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder> 
        getAccountsOrBuilderList() {
      return accounts_;
    }
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    public int getAccountsCount() {
      return accounts_.size();
    }
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber getAccounts(int index) {
      return accounts_.get(index);
    }
    /**
     * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
     */
    public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder getAccountsOrBuilder(
        int index) {
      return accounts_.get(index);
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      email_ = "";
      accounts_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAccountsCount(); i++) {
        if (!getAccounts(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < accounts_.size(); i++) {
        output.writeMessage(4, accounts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < accounts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, accounts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobufDemo.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.class, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder.class);
      }

      // Construct using com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAccountsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          accountsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_Person_descriptor;
      }

      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person getDefaultInstanceForType() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.getDefaultInstance();
      }

      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person build() {
        com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person buildPartial() {
        com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person result = new com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (accountsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            accounts_ = java.util.Collections.unmodifiableList(accounts_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.accounts_ = accounts_;
        } else {
          result.accounts_ = accountsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person) {
          return mergeFrom((com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person other) {
        if (other == com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (accountsBuilder_ == null) {
          if (!other.accounts_.isEmpty()) {
            if (accounts_.isEmpty()) {
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAccountsIsMutable();
              accounts_.addAll(other.accounts_);
            }
            onChanged();
          }
        } else {
          if (!other.accounts_.isEmpty()) {
            if (accountsBuilder_.isEmpty()) {
              accountsBuilder_.dispose();
              accountsBuilder_ = null;
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000008);
              accountsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAccountsFieldBuilder() : null;
            } else {
              accountsBuilder_.addAllMessages(other.accounts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getAccountsCount(); i++) {
          if (!getAccounts(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
       *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
       *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
       *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
       *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
       *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
       *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
       *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
       *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
       *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
       *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *Data Type can be anything as bool, int32, float, double, and string or user defined as AccountType
       *= 1,2 is unique tags given. Number 1-15 required less code encoding than higher number
       *Required--if field required, optional -0 or 1 occurrence, repeated - 0 to may occurrence
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 id = 2;
      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated .protobufDemo.Person.AccountNumber accounts = 4;
      private java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber> accounts_ =
        java.util.Collections.emptyList();
      private void ensureAccountsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          accounts_ = new java.util.ArrayList<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber>(accounts_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder> accountsBuilder_;

      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber> getAccountsList() {
        if (accountsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accounts_);
        } else {
          return accountsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public int getAccountsCount() {
        if (accountsBuilder_ == null) {
          return accounts_.size();
        } else {
          return accountsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber getAccounts(int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);
        } else {
          return accountsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder setAccounts(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.set(index, value);
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder setAccounts(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.set(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder addAccounts(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder addAccounts(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(index, value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder addAccounts(
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder addAccounts(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder addAllAccounts(
          java.lang.Iterable<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber> values) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          super.addAll(values, accounts_);
          onChanged();
        } else {
          accountsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder clearAccounts() {
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          accountsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public Builder removeAccounts(int index) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.remove(index);
          onChanged();
        } else {
          accountsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder getAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder getAccountsOrBuilder(
          int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);  } else {
          return accountsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public java.util.List<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder> 
           getAccountsOrBuilderList() {
        if (accountsBuilder_ != null) {
          return accountsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accounts_);
        }
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder addAccountsBuilder() {
        return getAccountsFieldBuilder().addBuilder(
            com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder addAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().addBuilder(
            index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufDemo.Person.AccountNumber accounts = 4;</code>
       */
      public java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder> 
           getAccountsBuilderList() {
        return getAccountsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder> 
          getAccountsFieldBuilder() {
        if (accountsBuilder_ == null) {
          accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumber.Builder, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.AccountNumberOrBuilder>(
                  accounts_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          accounts_ = null;
        }
        return accountsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobufDemo.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobufDemo.Person)
  }

  public interface PersonAccountsBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .protobufDemo.Person person = 1;
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person> 
        getPersonList();
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person getPerson(int index);
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    java.util.List<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobufDemo.PersonAccountsBook}
   */
  public static final class PersonAccountsBook extends
      com.google.protobuf.GeneratedMessage
      implements PersonAccountsBookOrBuilder {
    // Use PersonAccountsBook.newBuilder() to construct.
    private PersonAccountsBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonAccountsBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonAccountsBook defaultInstance;
    public static PersonAccountsBook getDefaultInstance() {
      return defaultInstance;
    }

    public PersonAccountsBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonAccountsBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_PersonAccountsBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_PersonAccountsBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook.class, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonAccountsBook> PARSER =
        new com.google.protobuf.AbstractParser<PersonAccountsBook>() {
      public PersonAccountsBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonAccountsBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonAccountsBook> getParserForType() {
      return PARSER;
    }

    // repeated .protobufDemo.Person person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person> person_;
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    public java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    public java.util.List<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .protobufDemo.Person person = 1;</code>
     */
    public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobufDemo.PersonAccountsBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_PersonAccountsBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_PersonAccountsBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook.class, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook.Builder.class);
      }

      // Construct using com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.internal_static_protobufDemo_PersonAccountsBook_descriptor;
      }

      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook getDefaultInstanceForType() {
        return com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook.getDefaultInstance();
      }

      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook build() {
        com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook buildPartial() {
        com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook result = new com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook) {
          return mergeFrom((com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook other) {
        if (other == com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonAccountsBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .protobufDemo.Person person = 1;
      private java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder addPerson(com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder addPerson(
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public java.util.List<? extends com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .protobufDemo.Person person = 1;</code>
       */
      public java.util.List<com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.Person.Builder, com.jbksoft.protobuf.protobufferData.PersonAccountsBookProtos.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobufDemo.PersonAccountsBook)
    }

    static {
      defaultInstance = new PersonAccountsBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobufDemo.PersonAccountsBook)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufDemo_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufDemo_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufDemo_Person_AccountNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufDemo_Person_AccountNumber_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufDemo_PersonAccountsBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufDemo_PersonAccountsBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PersonAccount.proto\022\014protobufDemo\"\363\001\n\006" +
      "Person\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005emai" +
      "l\030\003 \001(\t\0224\n\010accounts\030\004 \003(\0132\".protobufDemo" +
      ".Person.AccountNumber\032W\n\rAccountNumber\022\016" +
      "\n\006number\030\001 \002(\t\0226\n\004type\030\002 \001(\0162 .protobufD" +
      "emo.Person.AccountType:\006SAVING\"1\n\013Accoun" +
      "tType\022\014\n\010CHECKING\020\000\022\n\n\006SAVING\020\001\022\010\n\004VISA\020" +
      "\002\":\n\022PersonAccountsBook\022$\n\006person\030\001 \003(\0132" +
      "\024.protobufDemo.PersonB@\n$com.jbksoft.pro" +
      "tobuf.protobufferDataB\030PersonAccountsBoo",
      "kProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobufDemo_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobufDemo_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobufDemo_Person_descriptor,
              new java.lang.String[] { "Name", "Id", "Email", "Accounts", });
          internal_static_protobufDemo_Person_AccountNumber_descriptor =
            internal_static_protobufDemo_Person_descriptor.getNestedTypes().get(0);
          internal_static_protobufDemo_Person_AccountNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobufDemo_Person_AccountNumber_descriptor,
              new java.lang.String[] { "Number", "Type", });
          internal_static_protobufDemo_PersonAccountsBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobufDemo_PersonAccountsBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobufDemo_PersonAccountsBook_descriptor,
              new java.lang.String[] { "Person", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
